config/routes.rb
Rails.application.routes.draw do
  get '/' => 'pages#index', as: 'pages'

  get '/users/new' => 'users#new', as: 'new_user'
  post '/users' => 'users#create'

  get '/session/new' => 'session#new', as: 'new_session'
  post '/session' => 'session#create'
  get '/logout' => 'session#logout'

  get '/surveys' => 'surveys#index'
  get '/surveys/new' => 'surveys#new', as: 'new_survey'
  post '/surveys' => 'surveys#create'
  get '/surveys/:id' => 'surveys#show', as: 'show_survey'
  get '/surveys/:id/edit' => 'surveys#edit', as: 'edit_survey'
  patch '/surveys/:id' => 'surveys#patch', as: 'patch_survey'

  get '/questions' => 'questions#index'
  get '/questions/new' => 'questions#new', as: 'new_question'
  post '/questions' => 'questions#create'
  get '/questions/:id/edit' => 'questions#edit', as: 'edit_question'
  patch '/questions/:id' => 'questions#patch', as: 'patch_question'
  get '/questions/:id' => 'questions#show', as: 'show_question'
  delete '/questions/:id' => 'questions#delete', as: 'delete_question'

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :survey
  has_one :creator, through: :survey

end

app/models/survey.rb
class Survey < ActiveRecord::Base

  belongs_to :creator, class_name: "User"
  has_many :questions
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :surveys, foreign_key: :creator_id
  has_many :questions, through: :surveys

  has_secure_password

  validates :email, presence: true
  validates :email, uniqueness: true, on: :create # allows duplicate for updating
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :role, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate!
  before_action :authorize!, only: [:new, :create, :edit, :patch, :delete]

  def new
    @survey = Survey.find(params[:format])
  end
  
  def show
    @question = Question.find(params[:id])
    @surveys_questions = @question.survey.questions
    this_question_position = @surveys_questions.index(@question)
    unless this_question_position == 0
      @previous_question = @surveys_questions[this_question_position-1]
    end
    unless this_question_position == @surveys_questions.length-1
      @next_question = @surveys_questions[this_question_position+1]
    end
  end

  def create
    @question = Question.new(question_params)
    @survey = Survey.find(@question.survey_id)
    if @question.save
      redirect_to show_survey_path(@survey)
    else
      redirect_to new_question_path(@survey), flash: { error: @question.errors.messages }
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def patch
    @question = Question.find(params[:id])
    @question.update(question_params)
    redirect_to show_question_path(@question)
  end

  def delete
    question = Question.find(params[:id])
    @survey = Survey.find(question.survey_id)
    question.destroy
    redirect_to show_survey_path(@survey)
  end

  private

    def question_params
      params.require(:question).permit(:survey_id, :question_text, :choice_one, :choice_two, :choice_three, :choice_four)
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      login(@user)
      redirect_to surveys_path
    else
      redirect_to new_session_path(@user), flash: { error: "Invalid credentials, please try again." }
    end
  end

  def new
    @user = User.new
  end

  def logout
    session.delete(:user_id)
    redirect_to pages_path
  end

  def login(user)
    session[:user_id] = user.id
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  before_action :authenticate!
  before_action :authorize!, only: [:new, :create, :patch]

  def index
    @surveys = Survey.all
  end

  def new
    # @survey = Survey.new
  end

  def show
    @survey = Survey.find(params[:id])
  end

  def create
    @survey = Survey.new(survey_params)
    @survey.update(creator_id: current_user.id)
    if @survey.save
      respond_to do |format|
        # format.json { render partial: 'survey_title_row', locals: { survey: @survey } }
        format.html { redirect_to surveys_path }
      end
    # else
    #   p "survey not saved :("
    #   puts @survey.errors.messages
    #   p "~~~~~~~~~~~~~~~~~~~~~"
    #   if request.xhr?
    #     render json: { error: @survey.errors.messages }
    #   else
    #     redirect_to new_survey_path(@survey), flash: { error: @survey.errors.messages }
    #   end
    end
  end

  def patch
    @survey = Survey.find(params[:id])
    @survey.update(finalized?: true)
    if request.xhr?
      render json: { survey: @survey, questions: @survey.questions }
    else 
      redirect_to surveys_path
    end
  end

  private

    def survey_params
      params.require(:survey).permit(:title)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      if @user.role == ENV["COURSE_AUTHOR_SECRET_KEY"]
        @user.update(role: "Course Author")
      else
        @user.update(role: "Student")
      end
      session[:user_id] = @user.id
      redirect_to surveys_path
    else 
      redirect_to new_user_path(@user), flash: { error: @user.errors.messages }
    end

  end


  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def logged_in?
    session[:user_id]
  end

  def current_user
    if logged_in?
      User.find(session[:user_id])
    end
  end

  def authenticate!
    redirect_to pages_path unless logged_in?
  end

  def authorize!
    redirect_to pages_path unless current_user.role == "Course Author"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyWidget</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<nav class="row">
  <% if logged_in? %>
    <div class="col s8 m8 l8 left-align welcome"><%= "Welcome #{current_user.first_name} #{current_user.last_name}! You are logged in as a #{current_user.role}" %></div>
    <%= link_to "VIEW SURVEYS", surveys_path, class: "col s2 m2 l2 center-align nav-link" %>
    <%= link_to "LOGOUT", logout_path, class: "col s2 m2 l2 center-align nav-link" %>
  <% else %>
    <%= link_to "LOGIN", new_session_path, class: "col s2 offset-s8 m2 offset-m6 l2 offset-l8 center-align nav-link" %>
    <%= link_to "REGISTER", new_user_path, class: "col s2 m2 l2 center-align modal-trigger nav-link" %>
  <% end %>
</nav>

<body>
  
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="row">
  <h1 class="col s12 m12 l12 page-title">Welcome to the survey widget!</h1>
</div>

<div class="center-align buttons">
  <%= link_to "LOGIN", new_session_path, class: "waves-effect waves-light btn-large" %><br>
  <%= link_to "REGISTER", new_user_path, class: "waves-effect waves-light btn-large" %>
</div>

app/views/questions/edit.html.erb
<div class="survey-form">
  <%= form_for :question, method: 'PATCH', url: "/questions/#{@question.id}" do |f| %>
    <% if flash[:error] %>
      <div class="error-explanation">
        <% flash[:error].each do |error| %>
          <p class="error"><%= "#{error[0]} #{error[1][0]}" %></p>
        <% end %>
      </div>
    <% end %>

    <div class="user-action">
      <%= f.label :question_text, "QUESTION", class: "form-label question-field" %><br>
      <%= f.text_area :question_text, class: "question-entry-field question-field"%><br>

      <%= f.label :choice_one, "FIRST ANSWER CHOICE", class: "form-label" %><br>
      <%= f.text_area :choice_one, class: "question-entry-field" %><br>

      <%= f.label :choice_two, "SECOND ANSWER CHOICE", class: "form-label" %><br>
      <%= f.text_area :choice_two, class: "question-entry-field" %><br>

      <%= f.label :choice_three, "THIRD ANSWER CHOICE", class: "form-label" %><br>
      <%= f.text_area :choice_three, class: "question-entry-field" %><br>

      <%= f.label :choice_four, "FOURTH ANSWER CHOICE", class: "form-label" %><br>
      <%= f.text_area :choice_four, class: "question-entry-field" %><br>

      <div class="actions waves-effect waves-light btn-large extra-large-button">
        <%= f.submit "update question" %>
      </div>
    </div>

  <% end %>
</div>

app/views/questions/new.html.erb
<div class="survey-form">
  <%= form_for :question, url: questions_path(@question) do |f| %>
    <% if flash[:error] %>
      <div class="error-explanation">
        <% flash[:error].each do |error| %>
          <p class="error"><%= "#{error[0]} #{error[1][0]}" %></p>
        <% end %>
      </div>
    <% end %>

    <div class="user-action">
      <%= f.hidden_field :survey_id, value: "#{@survey.id}" %>
      <%= f.label :question_text, "QUESTION", class: "form-label question-field" %><br>
      <%= f.text_area :question_text, class: "question-entry-field question-field"%><br>

      <%= f.label :choice_one, "FIRST ANSWER CHOICE", class: "form-label" %><br>
      <%= f.text_area :choice_one, class: "question-entry-field" %><br>

      <%= f.label :choice_two, "SECOND ANSWER CHOICE", class: "form-label" %><br>
      <%= f.text_area :choice_two, class: "question-entry-field" %><br>

      <%= f.label :choice_three, "THIRD ANSWER CHOICE", class: "form-label" %><br>
      <%= f.text_area :choice_three, class: "question-entry-field" %><br>

      <%= f.label :choice_four, "FOURTH ANSWER CHOICE", class: "form-label" %><br>
      <%= f.text_area :choice_four, class: "question-entry-field" %><br>

      <div class="actions waves-effect waves-light btn-large extra-large-button">
        <%= f.submit "add question" %>
      </div>
    </div>

  <% end %>
</div>

app/views/questions/show.html.erb
<div class="survey-container">
  <h1 class="page-title"><%= @question.question_text %></h1>
  <ul>
    <li class="answer-choices"><%= @question.choice_one %></li>
    <li class="answer-choices"><%= @question.choice_two %></li>
    <li class="answer-choices"><%= @question.choice_three %></li>
    <li class="answer-choices"><%= @question.choice_four %></li>
  </ul>

  <div class="row">
    <% if current_user == @question.creator %>
      <% if @previous_question %>
        <%= link_to "Previous question", show_question_path(@previous_question), class:"col s3 m3 l3 left-align" %>
        <%= link_to "Edit question", edit_question_path(@question), class: "col s3 m3 l3 center-align" %> 
        <%= button_to "Delete question", delete_question_path(@question), method: "delete", class: "col s3 m3 l3 center-align delete-button" %>      
        <% if @next_question %>
          <%= link_to "Next question", show_question_path(@next_question), class: "col s3 m3 l3 right-align" %>
        <% end %>
      <% else %>
        <%= link_to "Edit question", edit_question_path(@question), class: "col s3 offset-s3 m3 offset-m3 l3 offset-l3 center-align" %>
        <%= button_to "Delete question", delete_question_path(@question), method: "delete", class: "col s3 m3 l3 center-align delete-button" %>
        <% if @next_question %>
          <%= link_to "Next question", show_question_path(@next_question), class: "col s3 m3 l3 right-align" %>
        <% end %>

      <% end %>
    <% else %>
      <% if @previous_question %>
        <%= link_to "Previous question", show_question_path(@previous_question), class:"col s9 m9 l9 left-align" %>
        <% if @next_question %>
          <%= link_to "Next question", show_question_path(@next_question), class: "col s3 m3 l3 right-align" %>
        <% end %>
      <% else %>
        <% if @next_question %>
          <%= link_to "Next question", show_question_path(@next_question), class: "col s12 m12 l12 right-align" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="survey-container">
<p class="question-notes"><span class="question-field">Current survey:</span> <%= @question.survey.title %></p>
<% if current_user != @question.creator %>
  <p class="question-notes">Only the author of this survey may edit or delete its questions</p>
<% end %>
</div>

app/views/session/new.html.erb
<div class="container general-form">
  <%= form_for :session, url: session_path(@user) do |f| %>
    <% if flash[:error] %>
      <div class="error-explanation">
        <p class="error"><%= flash[:error] %></p>
      </div>
    <% end %>

    <div class="user-action">
      <%= f.label :first_name, "First Name", class: "form-label" %><br>
      <%= f.text_field :first_name %>

      <%= f.label :last_name, "Last Name", class: "form-label" %><br>
      <%= f.text_field :last_name %>

      <%= f.label :password, "Password", class: "form-label" %><br>
      <%= f.password_field :password %>

      <%= f.label :email, "Email", class: "form-label" %><br>
      <%= f.text_field :email %>

      <div class="actions waves-effect waves-light btn-large">
        <%= f.submit "login" %>
      </div>
    </div>

  <% end %>
</div>

app/views/surveys/_survey_title_row.html.erb
<tr class="details-row">
  <td class="left-align"><%= survey.title %></td>
  <td class="right-align"><%= survey.id %></td>
  <% if survey.creator == current_user %>
    <!-- <td class="right-align">Edit Title</td> -->
    <td class="right-align">Finalize Survey</td>
    <!-- <td class="right-align">Delete Survey</td> -->
  <% end %>
</tr>

app/views/surveys/_surveys.html.erb
<table class="survey-list">
  <% finalized_surveys = [] %>
  <% @surveys.each do |survey| %>
    <% if survey.finalized? %>
      <% finalized_surveys << survey %>
    <% else %>
      <tr class="details-row">
        <td class="left-align"><%= link_to "#{survey.title}", show_survey_path(survey) %></td>
        <% if survey.creator == current_user %>
          <td><%= button_to "Finalize Survey", patch_survey_path(survey), method: "patch", class: "col s3 m3 l3 center-align delete-button finalize" %>
        <% end %>
      </tr>
    <% end %>
  <% end %>
</table>

<% unless finalized_surveys.length == 0 %>
  <div class="row">
    <h1 class="col s12 m12 l12 page-title">Finalized Surveys</h1>
  </div>

  <table class="survey-list">
    <% finalized_surveys.each do |survey| %>
      <tr class="details-row">
        <td class="left-align"><%= link_to "#{survey.title}", show_survey_path(survey) %></td>
        <td><%= survey.updated_at.strftime("Finalized on %B %-d, %Y") %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/surveys/index.html.erb
<div class="row">
  <h1 class="col s12 m12 l12 page-title">Active Surveys</h1>
  <h2 class="explanation">Click on a survey's title to see and/or edit its questions</h2>
</div>

  <%= render partial: 'surveys', locals: { surveys: @surveys } %>

<% if current_user.role == "Course Author" %>
  <div class="center-align buttons">
    <%= link_to "ADD NEW SURVEY", new_survey_path, class:"waves-effect waves-light btn-large extra-large-button"%>
  </div>
<% end %>

<!-- This modal isn't working. Hoping to come back to it before I'm done even if just to make it a div that toggles visibility. Need to get questions working first for MVP. -->
<div id="survey-modal" class="modal">
  <div class="modal-content">
    <h4>Please enter the title of your new survey?</h4>
    <%= form_for :survey, remote: true, url: surveys_path do |f| %>
      <%= f.text_field :title, id:"new-title"%>
      <div class="modal-footer">
        <a href="surveys" class="modal-action modal-close waves-effect waves-light btn-large extra-large-button">Create Survey</a>
        <!-- I wonder if the problem is that this is a link and not a button? -->
      </div>
    <% end %>
  </div>
</div>

app/views/surveys/new.html.erb
<div class="survey-form">
  <h4>Please enter the title of your new survey</h4>
  <%= form_for :survey, remote: true, url: surveys_path do |f| %>
    <%= f.text_field :title, id:"new-title"%><br>
    <div class="actions waves-effect waves-light btn-large extra-large-button">
        <%= f.submit "create new survey" %>
      </div>
  <% end %>
</div>

app/views/surveys/show.html.erb
<h1 class="page-title"><%= @survey.title %></h1>

<div class="survey-container">
  <ul>
    <% @survey.questions.each do |question| %>
      <li><%= link_to "#{question.question_text}", show_question_path(question) %></li>
  <% end %>
  </ul>

  <div class="row">
    <% if current_user == @survey.creator && !@survey.finalized?%>
      <%= link_to "Add question", new_question_path(@survey), class: "col s4 offset-s4 m4 offset-m4 l4 offset-l4 actions waves-effect waves-light btn-large extra-large-button" %>    
    <% end %>
  </div>
 </div>

<% if current_user != @survey.creator %>
  <div class="survey-container">
    <p class="question-notes">Only the author of this survey may add a question.</p>
  </div>
<% end %>
<% if @survey.finalized? %>
  <div class="survey-container">
    <p class="question-notes">Finalized surveys may not be changed.</p>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="container general-form">
  <%= form_for :user, url: users_path(@user) do |f| %>
    <% if flash[:error] %>
      <div class="error-explanation">
        <% flash[:error].each do |error| %>
          <p class="error"><%= "#{error[0]} #{error[1][0]}" %></p>
        <% end %>
      </div>
    <% end %>

    <div class="user-action">
      <%= f.label :first_name, "First Name", class: "form-label" %><br>
      <%= f.text_field :first_name %><br>

      <%= f.label :last_name, "Last Name", class: "form-label" %><br>
      <%= f.text_field :last_name %>

      <%= f.label :password, "Password", class: "form-label" %><br>
      <%= f.password_field :password %>

      <%= f.label :email, "Email", class: "form-label" %><br>
      <%= f.text_field :email %>

      <%= f.label :role, "Secret Key", class: "form-label" %><br>
      <%= f.text_field :role %>

      <div class="actions waves-effect waves-light btn-large extra-large-button">
        <%= f.submit "register as new user" %>
      </div>
    </div>

  <% end %>
</div>